geometry_msgs/PoseStamped pose  # End-effector pickup pose
bool lift                       # Flag for arm lifting after pickup
bool verify                     # Flag for grasp verification after gripper close/lift
---
bool success  # True on successful pickup
---
string message  # The current state message