controller_list:
 - name: jaco_arm/joint_velocity_controller
   action_ns: trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - jaco_joint_1
     - jaco_joint_2
     - jaco_joint_3
     - jaco_joint_4
     - jaco_joint_5
     - jaco_joint_6
 - name: jaco_arm/fingers_controller
   action_ns: gripper
   type: GripperCommand
   default: true
   joints:
     - jaco_joint_finger_1
     - jaco_joint_finger_2
     - jaco_joint_finger_3
