sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera/depth_registered/image_raw
    queue_size: 5
    near_clipping_plane_distance: 0.8
    far_clipping_plane_distance: 3
    shadow_threshold: 0.2
    padding_scale: 5.0
    padding_offset: 0.03
    filtered_cloud_topic: filtered_cloud
