sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /camera/depth_registered/points
   max_range: 3.0
   padding_offset: .05
   padding_scale: 1
   point_subsample: 10
